openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
paths:
  /authors:
    post:
      operationId: create
      tags:
      - Authors
      summary: create
      description: Create author
      requestBody:
        content:
          application/json:
            schema:
              properties:
                Email:
                  type: string
                Name:
                  type: string
              type: object
      responses:
        "200":
          description: Response for status code 200
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties:
                    Email:
                      type: string
                      default: String
                    ID:
                      type: number
                      default: 1
                    Name:
                      type: string
                      default: Author 1
                    Users:
                      type: array
                      items:
                        type: object
                        properties:
                          ID:
                            type: number
                            default: 1
                          Name:
                            type: string
                            default: User 1
                          Profile:
                            type: object
                            properties:
                              ID:
                                type: number
                                default: 1
                              Name:
                                type: string
                                default: Profile 1
                type: array
        "300":
          description: Response for status code 300
          content:
            application/json:
              schema:
                default: Redirect
                type: string
        "400":
          description: Response for status code 400
          content:
            application/json:
              schema:
                properties:
                  items:
                    type: object
                    properties:
                      Email:
                        type: string
                        default: String
                      ID:
                        type: number
                        default: 1
                      Name:
                        type: string
                        default: Author 1
                      Users:
                        type: array
                        items:
                          type: object
                          properties:
                            ID:
                              type: number
                              default: 1
                            Name:
                              type: string
                              default: User 1
                            Profile:
                              type: object
                              properties:
                                ID:
                                  type: number
                                  default: 1
                                Name:
                                  type: string
                                  default: Profile 1
                type: object
        "500":
          description: Response for status code 500
          content:
            application/json:
              schema:
                properties:
                  error:
                    type: string
                    default: Internal Server Error
                  status_code:
                    type: number
                    default: 500
                type: object
